### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by cobanov** [FrenchGithubUser/Hatt#5]

**Comment by FrenchGithubUser** [comment]
The framework I use (wails) does not support linux->macOS cross-compilation. A friend of mine has a mac running macOS and sometimes compiles binaries. For now, either looks at the previous build, or compile Hatt from source (which is relatively fast and easy, as explained in the readme).

**Comment by jebediah2** [comment]
None of the previous releases have a mac version. If compiling is 'relatively fast and easy' then why let all users do it themselves instead of doing it once for everyone to use?

**Comment by FrenchGithubUser** [comment]
@jebediah2 this is because, as I said, it is not possible to cross-compile binaries with wails for macOS. As I do not own a mac myself, I am not able to create macOS binaries.

About the previous builds, this repository has been temporarily suspended by github and the builds before the suspension have been hidden.

If cross-compilation for macOS with wails becomes a thing, I will upload macOS builds.
